#!/bin/bash

export CC="gcc"
export CFLAGS="-m32"
export LDFLAGS="-m32"
export ABI=32

host_config_opts="\
	--disable-longdouble \
	--enable-unicode=no \
        --enable-boehm=included \
	--enable-threads=yes \
	--with-debug-cflags=yes \
	--with-clx=no \
	--with-serve-event=no \
	--with-tcp=builtin \
	--with-x=no \
	--with-rt=no \
	--with-defsystem=no \
	--with-fpe=yes \
	--with-profile=no \
	--with-dffi=no \
	--with-asdf=yes \
	--with-bytecmp=builtin \
	--with-cmp=builtin"



./configure $host_config_opts $*
