#!/bin/bash

enable_threads=yes

#export CFLAGS="-DGC_LINUX_THREADS=1 -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DSILENT=1 -DNO_SIGNALS=1 -DNO_EXECUTE_PERMISSION=1 -DJAVA_FINALIZATION=1 -DGC_GCJ_SUPPORT=1 -DATOMIC_UNCOLLECTABLE=1 -D_IN_LIBGC=1  -DGC_LINUX_THREADS -D_GNU_SOURCE -D_REENTRANT -DUSE_MMAP -DUSE_MUNMAP -D_FILE_OFFSET_BITS=64 -DNO_UNALIGNED_ACCESS"

#export CFLAGS="-DHAVE_PTHREAD_GETATTR_NP -DHAVE_PTHREAD_ATTR_GETSTACK"


host_config_opts="\
	--disable-longdouble \
	--enable-unicode \
        --enable-boehm=included \
	--enable-threads=$enable_threads \
	--with-asdf=yes \
	--with-bytecmp=builtin \
	--with-cmp=builtin \
	--with-clx=no \
	--with-debug-cflags=yes \
	--with-defsystem=no \
	--with-fpe=yes \
	--with-profile=no \
	--with-rt=no \
	--with-serve-event=yes \
	--with-tcp=yes \
	--with-x=no \
	--with-dffi=no"


./configure $host_config_opts $*
